/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "text-muted": "#6B6B80",
          "surface-dim": "#131318",
          "primary-container": "#6c5ce7",
          "on-primary-fixed": "#160066",
          "on-tertiary-fixed-variant": "#005140",
          "outline-variant": "#474554",
          "on-tertiary-container": "#dffff1",
          "on-tertiary": "#00382b",
          "on-error": "#690005",
          "error": "#ffb4ab",
          "tertiary-container": "#008167",
          "outline": "#928ea0",
          "on-primary-fixed-variant": "#4029ba",
          "tertiary-fixed": "#6dfad2",
          "on-surface-variant": "#c8c4d7",
          "on-secondary-container": "#005250",
          "border-base": "#1E1E2E",
          "tertiary-fixed-dim": "#4bddb7",
          "background": "#0A0A0F",
          "surface": "#131318",
          "danger": "#D63031",
          "on-background": "#e4e1e9",
          "on-secondary-fixed": "#00201f",
          "secondary-fixed-dim": "#2edcd7",
          "on-secondary-fixed-variant": "#00504e",
          "surface-tint": "#c6bfff",
          "inverse-primary": "#5847d2",
          "on-primary": "#2900a0",
          "surface-container-high": "#2a292f",
          "on-tertiary-fixed": "#002018",
          "sidebar-active-glow": "rgba(108, 92, 231, 0.12)",
          "surface-bright": "#39383e",
          "text-primary": "#EAEAF0",
          "surface-container": "#1f1f25",
          "primary-fixed-dim": "#c6bfff",
          "inverse-surface": "#e4e1e9",
          "error-container": "#93000a",
          "card-bg": "#13131A",
          "on-surface": "#e4e1e9",
          "on-primary-container": "#faf6ff",
          "surface-container-low": "#1b1b20",
          "secondary": "#00CEC9",
          "surface-container-lowest": "#0e0e13",
          "on-secondary": "#003735",
          "primary-fixed": "#e4dfff",
          "surface-container-highest": "#35343a",
          "secondary-fixed": "#5af9f3",
          "tertiary": "#4bddb7",
          "primary": "#6C5CE7",
          "inverse-on-surface": "#303036",
          "surface-variant": "#35343a",
          "on-error-container": "#ffdad6",
          "secondary-container": "rgba(0, 206, 201, 0.1)",
          "border-input": "#2A2A3E",
          "status-applied": "#3B82F6",
          "status-review": "#F59E0B",
          "status-shortlist": "#6C5CE7",
          "status-interview": "#00CEC9",
          "status-hired": "#10B981"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "8px",
          "xl": "12px",
          "full": "9999px"
      },
      "spacing": {
          "xxl": "64px",
          "xs": "8px",
          "base-unit": "8px",
          "sm": "16px",
          "md": "24px",
          "container-max": "1280px",
          "xl": "48px",
          "gutter": "24px",
          "lg": "32px",
          "sidebar-width": "240px"
      },
      "fontFamily": {
          "display": ["Syne", "sans-serif"],
          "headline-lg": ["Syne", "sans-serif"],
          "headline-md": ["Syne", "sans-serif"],
          "headline-sm": ["Syne", "sans-serif"],
          "body-lg": ["DM Sans", "sans-serif"],
          "body-md": ["DM Sans", "sans-serif"],
          "body-sm": ["DM Sans", "sans-serif"],
          "label-md": ["DM Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
