import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const PrivacyPolicyPage = () => {
  return (
    <div className="bg-background text-text-primary font-body-md min-h-screen flex flex-col pt-24">
      <Navbar />

      <main className="flex-1 max-w-4xl mx-auto px-gutter py-20 w-full">
        {/* Title */}
        <div className="mb-12 border-b border-border-input pb-8">
          <h1 className="font-display text-4xl md:text-5xl font-extrabold text-white mb-4">Privacy Policy</h1>
          <p className="text-text-muted text-sm">Last updated: May 25, 2026</p>
        </div>

        {/* Policy Summary Box */}
        <div className="bg-surface-container border border-border-input p-6 rounded-xl mb-12">
          <h3 className="font-headline-sm font-bold text-white mb-2 flex items-center gap-2">
            <span className="material-symbols-outlined text-secondary">security</span>
            Privacy Highlights
          </h3>
          <p className="text-text-muted text-sm leading-relaxed mb-4">
            At Visume, your privacy is a paramount commitment. Here are the key highlights of how we handle your video resumes and profile data:
          </p>
          <ul className="grid md:grid-cols-2 gap-3 text-xs text-text-primary">
            <li className="flex items-center gap-2">
              <span className="material-symbols-outlined text-[16px] text-primary">circle</span>
              We do NOT sell your video files to third parties.
            </li>
            <li className="flex items-center gap-2">
              <span className="material-symbols-outlined text-[16px] text-primary">circle</span>
              You have complete control over who views your video.
            </li>
            <li className="flex items-center gap-2">
              <span className="material-symbols-outlined text-[16px] text-primary">circle</span>
              AI transcripts can be modified or hidden.
            </li>
            <li className="flex items-center gap-2">
              <span className="material-symbols-outlined text-[16px] text-primary">circle</span>
              Delete your account and all data instantly via settings.
            </li>
          </ul>
        </div>

        {/* Core Sections */}
        <div className="space-y-10 font-body-md text-text-muted leading-relaxed">
          <section className="space-y-4">
            <h2 className="font-display text-2xl font-bold text-white">1. Information We Collect</h2>
            <p>
              When you use Visume, we collect information that helps us provide a modern job matching service. This includes:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong className="text-white">Account Data:</strong> Your name, email address, password, and professional background when you register.
              </li>
              <li>
                <strong className="text-white">Video Resumes:</strong> The audio and video files you record or upload to showcase your profile.
              </li>
              <li>
                <strong className="text-white">AI Transcripts:</strong> Written transcripts and tone data generated by our AI processing systems.
              </li>
              <li>
                <strong className="text-white">Usage Analytics:</strong> Standard logs, device information, and site interaction metrics.
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-2xl font-bold text-white">2. How We Use Your Data</h2>
            <p>
              We process your personal information and media files for the following business purposes:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>To present your video profile to authorized recruiters you apply to.</li>
              <li>To run AI analysis that produces personality matching scores.</li>
              <li>To maintain, improve, and secure the web recording tools.</li>
              <li>To communicate support requests, matching notifications, and updates.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-2xl font-bold text-white">3. Data Sharing & Visibility</h2>
            <p>
              By default, your profile is visible to recruiters looking for matching tags on the platform. However, you can change your visibility settings at any time in your Settings panel. We will never lease, sell, or trade your video files or personal details with advertiser networks.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-2xl font-bold text-white">4. Data Security & Storage</h2>
            <p>
              We store all videos and user profiles on encrypted cloud infrastructure. Access is restricted using secure token authentication. While we utilize industry-standard measures to keep data safe, no transmission method over the Internet is 100% secure.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-2xl font-bold text-white">5. Your Privacy Rights</h2>
            <p>
              Depending on your location, you may have the right to access, update, export, or delete the personal information we hold about you. You can easily manage these options or request full data deletion by visiting your dashboard Settings page.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default PrivacyPolicyPage;
